"""create business tables

Revision ID: 35b4fd9dc5f3
Revises: 97b1ddf51c6c
Create Date: 2026-05-28 14:24:57.423115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35b4fd9dc5f3"
down_revision: Union[str, Sequence[str], None] = "97b1ddf51c6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column(
            "tier",
            sa.Enum("smb", "mid_market", "enterprise", name="customer_tier"),
            nullable=False,
        ),
        sa.Column("account_owner_user_id", sa.UUID(), nullable=True),
        sa.Column("contract_value", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "health_status",
            sa.Enum("healthy", "watch", "at_risk", "critical", name="customer_health"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_owner_user_id"], ["app_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "ix_customers_deleted_at", "customers", ["deleted_at"], unique=False
    )
    op.create_index(
        "ix_customers_health_status", "customers", ["health_status"], unique=False
    )
    op.create_index("ix_customers_name", "customers", ["name"], unique=False)
    op.create_table(
        "issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("external_ref", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "blocked",
                "resolved",
                "closed",
                name="issue_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("p1", "p2", "p3", "p4", name="issue_priority"),
            nullable=False,
        ),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=True),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"], ["app_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_ref"),
    )
    op.create_index(
        "ix_issues_assigned_to_user_id", "issues", ["assigned_to_user_id"], unique=False
    )
    op.create_index("ix_issues_customer_id", "issues", ["customer_id"], unique=False)
    op.create_index(
        "ix_issues_customer_id_status",
        "issues",
        ["customer_id", "status"],
        unique=False,
    )
    op.create_index("ix_issues_deleted_at", "issues", ["deleted_at"], unique=False)
    op.create_index("ix_issues_priority", "issues", ["priority"], unique=False)
    op.create_index("ix_issues_status", "issues", ["status"], unique=False)
    op.create_table(
        "issue_updates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column("author_user_id", sa.UUID(), nullable=True),
        sa.Column("author_name", sa.String(length=255), nullable=True),
        sa.Column("author_role", sa.String(length=50), nullable=True),
        sa.Column("update_text", sa.Text(), nullable=False),
        sa.Column("is_customer_visible", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["app_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_issue_updates_author_user_id",
        "issue_updates",
        ["author_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_issue_updates_issue_id", "issue_updates", ["issue_id"], unique=False
    )
    op.create_index(
        "ix_issue_updates_issue_id_created_at",
        "issue_updates",
        ["issue_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "next_actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issue_id", sa.UUID(), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "customer_update",
                "technical_investigation",
                "workaround_confirmation",
                "engineering_escalation",
                "account_escalation",
                "sla_review",
                "follow_up_meeting",
                "other",
                name="next_action_type",
            ),
            nullable=False,
        ),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "in_progress",
                "completed",
                "cancelled",
                name="next_action_status",
            ),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("created_by_role", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["app_users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["app_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_next_actions_created_by_user_id",
        "next_actions",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index("ix_next_actions_due_at", "next_actions", ["due_at"], unique=False)
    op.create_index(
        "ix_next_actions_issue_id", "next_actions", ["issue_id"], unique=False
    )
    op.create_index(
        "ix_next_actions_owner_user_id", "next_actions", ["owner_user_id"], unique=False
    )
    op.create_index("ix_next_actions_status", "next_actions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_next_actions_status", table_name="next_actions")
    op.drop_index("ix_next_actions_owner_user_id", table_name="next_actions")
    op.drop_index("ix_next_actions_issue_id", table_name="next_actions")
    op.drop_index("ix_next_actions_due_at", table_name="next_actions")
    op.drop_index("ix_next_actions_created_by_user_id", table_name="next_actions")
    op.drop_table("next_actions")
    op.drop_index("ix_issue_updates_issue_id_created_at", table_name="issue_updates")
    op.drop_index("ix_issue_updates_issue_id", table_name="issue_updates")
    op.drop_index("ix_issue_updates_author_user_id", table_name="issue_updates")
    op.drop_table("issue_updates")
    op.drop_index("ix_issues_status", table_name="issues")
    op.drop_index("ix_issues_priority", table_name="issues")
    op.drop_index("ix_issues_deleted_at", table_name="issues")
    op.drop_index("ix_issues_customer_id_status", table_name="issues")
    op.drop_index("ix_issues_customer_id", table_name="issues")
    op.drop_index("ix_issues_assigned_to_user_id", table_name="issues")
    op.drop_table("issues")
    op.drop_index("ix_customers_name", table_name="customers")
    op.drop_index("ix_customers_health_status", table_name="customers")
    op.drop_index("ix_customers_deleted_at", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
